version: "3"

services:
    proxy:
        build:
            context: .
            dockerfile: docker/proxy/Dockerfile
        ports:
            - "443:443"
            - "8080:8080"
            - "9999:9999"
        privileged: true
        network_mode: "host"
    filter:
        build:
            context: .
            dockerfile: docker/filter/Dockerfile
        ports:
            - "8081:8081"
        network_mode: "host"
    nodeos:
        image: eosio/eos
        command: /opt/eosio/bin/nodeosd.sh -e --data-dir /opt/eosio/bin/data-dir --http-alias=localhost:8888
        ports:
            - "8888:8888"
            - "9876:9876"
        expose:
            - "8888"        

